# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://false-l.github.io
date_format: "ordinal"
title: WaterServer
subtitle: "life is brief, and then you die, you know?"
description: "YL的个人博客"
keywords: waterserver, false-l, YlLin
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 3

# ---------------- #
#      Author      #
# ---------------- #
author: YL Lin
organization: none
organization_url: none
location: Zhe Jiang, China
email: waterservers@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /tags/
    label: 标签

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 4
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /tags/:path/

#repository: mzlogin/mzlogin.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: False-L
douban_username: waterserver
facebook_username: 
weibo_username: waterserver
zhihu_username: lastlife
twitter_username: 

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: 永恒的心
disqus_username: waterserver
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: 

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [C, C++, Html, JavaScript, jQuery, PHP]
skill_windows_keywords: [Win32, Linux]
